### ISSUE TITLE
CircleTransofrmation sometimes crashes

### ISSUE THREAD

**Issue by hkurokawa** [hkurokawa/Qiitandroid#5]
Stacktrace:

```
08-19 17:32:53.374  18325-18325/com.hkurokawa.qiitandroid E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.hkurokawa.qiitandroid, PID: 18325
    java.lang.RuntimeException: Transformation circle crashed with exception.
            at com.squareup.picasso.BitmapHunter$3.run(BitmapHunter.java:434)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
            at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
            at com.hkurokawa.qiitandroid.views.CircleTransformation.transform(CircleTransformation.java:27)
            at com.squareup.picasso.BitmapHunter.applyCustomTransformations(BitmapHunter.java:429)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:238)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by hkurokawa** [comment]
The error seems occur at the below line in CircleTransformataion.java

```
27     final Bitmap bitmap = Bitmap.createBitmap(size, size, source.getConfig());
```

`source.getConfig()` seems `null`.
